### ISSUE TITLE
Update enablers.json file

### ISSUE THREAD

**Issue by flopezag** [flopezag/fiware-clair#1]
We need to add the complete set of FIWARE GEs docker images into the enablers.json file

**Comment by caa06d9c** [comment]
It should be a simple list of GEs?

**Comment by caa06d9c** [comment]
We have this [tool](https://github.com/FIWARE-Ops/Tools/tree/master/GetDockerHubInfo), it can be updated to prepare json instead of xlsx.

**Comment by flopezag** [comment]
What we need is a simple list of GEs described by its name and the docker image, how it is shown in this  [enablers.json](https://github.com/flopezag/fiware-clair/blob/develop/docker/enablers.json) file.

**Comment by caa06d9c** [comment]
Fixed by https://github.com/flopezag/fiware-clair/pull/5
